// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/microts.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 字段值
//
// Point 的字段值使用 oneof 支持多种数据类型。
// 存储引擎会根据值的实际类型进行相应的编码和处理。
//
// 支持的类型：
//
//   - int_value: 64位有符号整数，适用于计数器、ID 等
//   - float_value: 64位浮点数，适用于温度、电压等连续值
//   - string_value: 可变长度字符串，适用于状态描述
//   - bool_value: 布尔值，适用于开关状态
//
// 类型说明：
//
//	写入时根据值的类型自动选择对应的字段。
//	查询时根据实际存储的类型返回相应值。
type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FieldValue_IntValue
	//	*FieldValue_FloatValue
	//	*FieldValue_StringValue
	//	*FieldValue_BoolValue
	Value         isFieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_proto_microts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{0}
}

func (x *FieldValue) GetValue() isFieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FieldValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *FieldValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isFieldValue_Value interface {
	isFieldValue_Value()
}

type FieldValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type FieldValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,2,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*FieldValue_IntValue) isFieldValue_Value() {}

func (*FieldValue_FloatValue) isFieldValue_Value() {}

func (*FieldValue_StringValue) isFieldValue_Value() {}

func (*FieldValue_BoolValue) isFieldValue_Value() {}

// 数据点
//
// Point 是写入时序数据库的基本数据单元。
// 每个 Point 代表时间序列中的一个数据点。
//
// 必需字段：
//
//   - database: 数据库名称，用于隔离不同业务的数据
//   - measurement: 测量名称，类似关系数据库的表名
//   - timestamp: 纳秒级 Unix 时间戳
//   - tags: 标签键值对，用于标识时间序列
//   - fields: 字段值，存储实际的数据
//
// 标签与字段的区别：
//
//	标签用于索引和分组，会被存储在 Series Key 中，查询效率高。
//	字段存储实际数据值，不会被索引，但可以存储大量不同的值。
//
// 最佳实践：
//
//	标签建议使用 host, region, service 等维度信息。
//	时间戳推荐使用 time.Now().UnixNano() 获取。
type Point struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据库名称
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// 测量名称（类似表名）
	Measurement string `protobuf:"bytes,2,opt,name=measurement,proto3" json:"measurement,omitempty"`
	// 标签键值对，用于标识时间序列
	Tags map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 时间戳，纳秒级 Unix 时间戳
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 字段值，存储实际的数据
	Fields        map[string]*FieldValue `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_microts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Point) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

func (x *Point) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Point) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Point) GetFields() map[string]*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 查询结果行
//
// PointRow 是查询结果的单行数据。
// 相比 Point，PointRow 增加了 SID 字段用于内部标识。
//
// 字段说明：
//
//   - sid: Series ID，内部生成的序列标识符（从1开始递增）
//   - timestamp: 数据点的时间戳（纳秒）
//   - tags: 标签键值对
//   - fields: 字段值
//
// SID 说明：
//
//	SID 由存储引擎为每个唯一的标签组合分配。
//	相同的标签组合始终对应同一个 SID。
//	用户通常不需要直接使用此字段。
type PointRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Series ID，用于内部标识唯一的标签组合
	Sid uint64 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	// 时间戳
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 标签键值对
	Tags map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 字段值
	Fields        map[string]*FieldValue `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointRow) Reset() {
	*x = PointRow{}
	mi := &file_proto_microts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointRow) ProtoMessage() {}

func (x *PointRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointRow.ProtoReflect.Descriptor instead.
func (*PointRow) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{2}
}

func (x *PointRow) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *PointRow) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PointRow) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PointRow) GetFields() map[string]*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 写入请求
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Measurement   string                 `protobuf:"bytes,2,opt,name=measurement,proto3" json:"measurement,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Fields        map[string]*FieldValue `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_microts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *WriteRequest) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

func (x *WriteRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *WriteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WriteRequest) GetFields() map[string]*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 批量写入请求
type WriteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*WriteRequest        `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchRequest) Reset() {
	*x = WriteBatchRequest{}
	mi := &file_proto_microts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchRequest) ProtoMessage() {}

func (x *WriteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchRequest.ProtoReflect.Descriptor instead.
func (*WriteBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{4}
}

func (x *WriteBatchRequest) GetPoints() []*WriteRequest {
	if x != nil {
		return x.Points
	}
	return nil
}

// 写入响应
type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_microts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{5}
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 批量写入响应
type WriteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchResponse) Reset() {
	*x = WriteBatchResponse{}
	mi := &file_proto_microts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchResponse) ProtoMessage() {}

func (x *WriteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchResponse.ProtoReflect.Descriptor instead.
func (*WriteBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{6}
}

func (x *WriteBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WriteBatchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 范围查询请求
type QueryRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Measurement   string                 `protobuf:"bytes,2,opt,name=measurement,proto3" json:"measurement,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Fields        []string               `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Offset        int64                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRangeRequest) Reset() {
	*x = QueryRangeRequest{}
	mi := &file_proto_microts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeRequest) ProtoMessage() {}

func (x *QueryRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeRequest.ProtoReflect.Descriptor instead.
func (*QueryRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRangeRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *QueryRangeRequest) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

func (x *QueryRangeRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryRangeRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryRangeRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *QueryRangeRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *QueryRangeRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryRangeRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 一行数据（用于查询响应）
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fields        map[string]*FieldValue `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_microts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{8}
}

func (x *Row) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Row) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Row) GetFields() map[string]*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 范围查询响应
type QueryRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Measurement   string                 `protobuf:"bytes,2,opt,name=measurement,proto3" json:"measurement,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalCount    int64                  `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,6,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,7,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRangeResponse) Reset() {
	*x = QueryRangeResponse{}
	mi := &file_proto_microts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeResponse) ProtoMessage() {}

func (x *QueryRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeResponse.ProtoReflect.Descriptor instead.
func (*QueryRangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRangeResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *QueryRangeResponse) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

func (x *QueryRangeResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryRangeResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryRangeResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *QueryRangeResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *QueryRangeResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// 列出 Measurement 请求
type ListMeasurementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeasurementsRequest) Reset() {
	*x = ListMeasurementsRequest{}
	mi := &file_proto_microts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeasurementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeasurementsRequest) ProtoMessage() {}

func (x *ListMeasurementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeasurementsRequest.ProtoReflect.Descriptor instead.
func (*ListMeasurementsRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{10}
}

func (x *ListMeasurementsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// 列出 Measurement 响应
type ListMeasurementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Measurements  []string               `protobuf:"bytes,1,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeasurementsResponse) Reset() {
	*x = ListMeasurementsResponse{}
	mi := &file_proto_microts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeasurementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeasurementsResponse) ProtoMessage() {}

func (x *ListMeasurementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeasurementsResponse.ProtoReflect.Descriptor instead.
func (*ListMeasurementsResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{11}
}

func (x *ListMeasurementsResponse) GetMeasurements() []string {
	if x != nil {
		return x.Measurements
	}
	return nil
}

// 创建 Measurement 请求
type CreateMeasurementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Measurement   string                 `protobuf:"bytes,2,opt,name=measurement,proto3" json:"measurement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeasurementRequest) Reset() {
	*x = CreateMeasurementRequest{}
	mi := &file_proto_microts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeasurementRequest) ProtoMessage() {}

func (x *CreateMeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeasurementRequest.ProtoReflect.Descriptor instead.
func (*CreateMeasurementRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{12}
}

func (x *CreateMeasurementRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *CreateMeasurementRequest) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

// 创建 Measurement 响应
type CreateMeasurementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeasurementResponse) Reset() {
	*x = CreateMeasurementResponse{}
	mi := &file_proto_microts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeasurementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeasurementResponse) ProtoMessage() {}

func (x *CreateMeasurementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeasurementResponse.ProtoReflect.Descriptor instead.
func (*CreateMeasurementResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{13}
}

func (x *CreateMeasurementResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateMeasurementResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 删除 Measurement 请求
type DropMeasurementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Measurement   string                 `protobuf:"bytes,2,opt,name=measurement,proto3" json:"measurement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropMeasurementRequest) Reset() {
	*x = DropMeasurementRequest{}
	mi := &file_proto_microts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropMeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropMeasurementRequest) ProtoMessage() {}

func (x *DropMeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropMeasurementRequest.ProtoReflect.Descriptor instead.
func (*DropMeasurementRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{14}
}

func (x *DropMeasurementRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DropMeasurementRequest) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

// 删除 Measurement 响应
type DropMeasurementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropMeasurementResponse) Reset() {
	*x = DropMeasurementResponse{}
	mi := &file_proto_microts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropMeasurementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropMeasurementResponse) ProtoMessage() {}

func (x *DropMeasurementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropMeasurementResponse.ProtoReflect.Descriptor instead.
func (*DropMeasurementResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{15}
}

func (x *DropMeasurementResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DropMeasurementResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 列出数据库请求
type ListDatabasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	mi := &file_proto_microts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{16}
}

// 列出数据库响应
type ListDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []string               `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_proto_microts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{17}
}

func (x *ListDatabasesResponse) GetDatabases() []string {
	if x != nil {
		return x.Databases
	}
	return nil
}

// 创建数据库请求
type CreateDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRequest) Reset() {
	*x = CreateDatabaseRequest{}
	mi := &file_proto_microts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRequest) ProtoMessage() {}

func (x *CreateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{18}
}

func (x *CreateDatabaseRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// 创建数据库响应
type CreateDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseResponse) Reset() {
	*x = CreateDatabaseResponse{}
	mi := &file_proto_microts_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseResponse) ProtoMessage() {}

func (x *CreateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{19}
}

func (x *CreateDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateDatabaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 删除数据库请求
type DropDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropDatabaseRequest) Reset() {
	*x = DropDatabaseRequest{}
	mi := &file_proto_microts_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatabaseRequest) ProtoMessage() {}

func (x *DropDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatabaseRequest.ProtoReflect.Descriptor instead.
func (*DropDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{20}
}

func (x *DropDatabaseRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// 删除数据库响应
type DropDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropDatabaseResponse) Reset() {
	*x = DropDatabaseResponse{}
	mi := &file_proto_microts_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatabaseResponse) ProtoMessage() {}

func (x *DropDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatabaseResponse.ProtoReflect.Descriptor instead.
func (*DropDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{21}
}

func (x *DropDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DropDatabaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 健康检查请求
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_microts_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{22}
}

// 健康检查响应
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_microts_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{23}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 内存表配置
//
// 内存表（MemTable）是写入缓冲区，数据先写入 MemTable，
// 当满足任一条件时刷新到 SSTable。
//
// 刷新条件（满足任一即触发）：
//
//   - max_size: 内存占用（估算）达到上限
//   - max_count: 条目数达到上限
//   - idle_duration_nanos: 超过空闲时间没有新数据写入（纳秒）
//
// 性能调优建议：
//
//	增加 max_size 可以减少刷盘频率，但会增加内存占用和恢复时间。
//	减少 idle_duration 可以更快释放内存，但会增加小文件数量。
//	max_count 主要作为后备保护。
//
// 默认值：
//
//   - max_size: 64MB
//   - max_count: 3000
//   - idle_duration_nanos: 60秒（60000000000纳秒）
type MemTableConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 最大内存大小（字节），默认 64MB
	MaxSize int64 `protobuf:"varint,1,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	// 最大条目数，默认 3000
	MaxCount int32 `protobuf:"varint,2,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	// 空闲时间阈值（纳秒），默认 60秒
	IdleDurationNanos int64 `protobuf:"varint,3,opt,name=idle_duration_nanos,json=idleDurationNanos,proto3" json:"idle_duration_nanos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MemTableConfig) Reset() {
	*x = MemTableConfig{}
	mi := &file_proto_microts_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemTableConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemTableConfig) ProtoMessage() {}

func (x *MemTableConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemTableConfig.ProtoReflect.Descriptor instead.
func (*MemTableConfig) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{24}
}

func (x *MemTableConfig) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *MemTableConfig) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *MemTableConfig) GetIdleDurationNanos() int64 {
	if x != nil {
		return x.IdleDurationNanos
	}
	return 0
}

// 引擎配置
//
// Config 是数据库的完整配置结构。
// 这是存储引擎使用的配置，包含数据目录、分片时长和内存表配置。
//
// 字段说明：
//
//   - data_dir: 数据存储目录路径
//   - shard_duration_nanos: Shard 时间窗口（纳秒），最小 1 小时
//   - mem_table_cfg: 内存表配置
//
// ShardDuration 说明：
//
//	ShardDuration 控制数据在磁盘上的分片大小。
//	较小的值会产生更多小文件，利于过期数据快速清理。
//	较大的值减少文件数量，提高大时间范围查询效率。
//	建议值：1小时(3600000000000) - 7天(604800000000000)。
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据目录
	DataDir string `protobuf:"bytes,1,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	// Shard 时间窗口（纳秒）
	ShardDurationNanos int64 `protobuf:"varint,2,opt,name=shard_duration_nanos,json=shardDurationNanos,proto3" json:"shard_duration_nanos,omitempty"`
	// 内存表配置
	MemTableCfg   *MemTableConfig `protobuf:"bytes,3,opt,name=mem_table_cfg,json=memTableCfg,proto3" json:"mem_table_cfg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proto_microts_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proto_microts_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proto_microts_proto_rawDescGZIP(), []int{25}
}

func (x *Config) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *Config) GetShardDurationNanos() int64 {
	if x != nil {
		return x.ShardDurationNanos
	}
	return 0
}

func (x *Config) GetMemTableCfg() *MemTableConfig {
	if x != nil {
		return x.MemTableCfg
	}
	return nil
}

var File_proto_microts_proto protoreflect.FileDescriptor

const file_proto_microts_proto_rawDesc = "" +
	"\n" +
	"\x13proto/microts.proto\x12\n" +
	"microts.v1\"\x9d\x01\n" +
	"\n" +
	"FieldValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x02 \x01(\x01H\x00R\n" +
	"floatValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"\xd7\x02\n" +
	"\x05Point\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12 \n" +
	"\vmeasurement\x18\x02 \x01(\tR\vmeasurement\x12/\n" +
	"\x04tags\x18\x03 \x03(\v2\x1b.microts.v1.Point.TagsEntryR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x125\n" +
	"\x06fields\x18\x05 \x03(\v2\x1d.microts.v1.Point.FieldsEntryR\x06fields\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.microts.v1.FieldValueR\x05value:\x028\x01\"\xb4\x02\n" +
	"\bPointRow\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\x04R\x03sid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x122\n" +
	"\x04tags\x18\x03 \x03(\v2\x1e.microts.v1.PointRow.TagsEntryR\x04tags\x128\n" +
	"\x06fields\x18\x04 \x03(\v2 .microts.v1.PointRow.FieldsEntryR\x06fields\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.microts.v1.FieldValueR\x05value:\x028\x01\"\xec\x02\n" +
	"\fWriteRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12 \n" +
	"\vmeasurement\x18\x02 \x01(\tR\vmeasurement\x126\n" +
	"\x04tags\x18\x03 \x03(\v2\".microts.v1.WriteRequest.TagsEntryR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12<\n" +
	"\x06fields\x18\x05 \x03(\v2$.microts.v1.WriteRequest.FieldsEntryR\x06fields\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.microts.v1.FieldValueR\x05value:\x028\x01\"E\n" +
	"\x11WriteBatchRequest\x120\n" +
	"\x06points\x18\x01 \x03(\v2\x18.microts.v1.WriteRequestR\x06points\"?\n" +
	"\rWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Z\n" +
	"\x12WriteBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xc7\x02\n" +
	"\x11QueryRangeRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12 \n" +
	"\vmeasurement\x18\x02 \x01(\tR\vmeasurement\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06fields\x18\x05 \x03(\tR\x06fields\x12;\n" +
	"\x04tags\x18\x06 \x03(\v2'.microts.v1.QueryRangeRequest.TagsEntryR\x04tags\x12\x16\n" +
	"\x06offset\x18\a \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\b \x01(\x03R\x05limit\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x02\n" +
	"\x03Row\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12-\n" +
	"\x04tags\x18\x02 \x03(\v2\x19.microts.v1.Row.TagsEntryR\x04tags\x123\n" +
	"\x06fields\x18\x03 \x03(\v2\x1b.microts.v1.Row.FieldsEntryR\x06fields\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.microts.v1.FieldValueR\x05value:\x028\x01\"\xed\x01\n" +
	"\x12QueryRangeResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12 \n" +
	"\vmeasurement\x18\x02 \x01(\tR\vmeasurement\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x03R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x06 \x01(\bR\ahasMore\x12#\n" +
	"\x04rows\x18\a \x03(\v2\x0f.microts.v1.RowR\x04rows\"5\n" +
	"\x17ListMeasurementsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\">\n" +
	"\x18ListMeasurementsResponse\x12\"\n" +
	"\fmeasurements\x18\x01 \x03(\tR\fmeasurements\"X\n" +
	"\x18CreateMeasurementRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12 \n" +
	"\vmeasurement\x18\x02 \x01(\tR\vmeasurement\"K\n" +
	"\x19CreateMeasurementResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x16DropMeasurementRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12 \n" +
	"\vmeasurement\x18\x02 \x01(\tR\vmeasurement\"I\n" +
	"\x17DropMeasurementResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x16\n" +
	"\x14ListDatabasesRequest\"5\n" +
	"\x15ListDatabasesResponse\x12\x1c\n" +
	"\tdatabases\x18\x01 \x03(\tR\tdatabases\"3\n" +
	"\x15CreateDatabaseRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"H\n" +
	"\x16CreateDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"1\n" +
	"\x13DropDatabaseRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"F\n" +
	"\x14DropDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"x\n" +
	"\x0eMemTableConfig\x12\x19\n" +
	"\bmax_size\x18\x01 \x01(\x03R\amaxSize\x12\x1b\n" +
	"\tmax_count\x18\x02 \x01(\x05R\bmaxCount\x12.\n" +
	"\x13idle_duration_nanos\x18\x03 \x01(\x03R\x11idleDurationNanos\"\x95\x01\n" +
	"\x06Config\x12\x19\n" +
	"\bdata_dir\x18\x01 \x01(\tR\adataDir\x120\n" +
	"\x14shard_duration_nanos\x18\x02 \x01(\x03R\x12shardDurationNanos\x12>\n" +
	"\rmem_table_cfg\x18\x03 \x01(\v2\x1a.microts.v1.MemTableConfigR\vmemTableCfg2\xc1\x06\n" +
	"\aMicroTS\x12<\n" +
	"\x05Write\x12\x18.microts.v1.WriteRequest\x1a\x19.microts.v1.WriteResponse\x12K\n" +
	"\n" +
	"WriteBatch\x12\x1d.microts.v1.WriteBatchRequest\x1a\x1e.microts.v1.WriteBatchResponse\x12K\n" +
	"\n" +
	"QueryRange\x12\x1d.microts.v1.QueryRangeRequest\x1a\x1e.microts.v1.QueryRangeResponse\x12]\n" +
	"\x10ListMeasurements\x12#.microts.v1.ListMeasurementsRequest\x1a$.microts.v1.ListMeasurementsResponse\x12`\n" +
	"\x11CreateMeasurement\x12$.microts.v1.CreateMeasurementRequest\x1a%.microts.v1.CreateMeasurementResponse\x12Z\n" +
	"\x0fDropMeasurement\x12\".microts.v1.DropMeasurementRequest\x1a#.microts.v1.DropMeasurementResponse\x12T\n" +
	"\rListDatabases\x12 .microts.v1.ListDatabasesRequest\x1a!.microts.v1.ListDatabasesResponse\x12W\n" +
	"\x0eCreateDatabase\x12!.microts.v1.CreateDatabaseRequest\x1a\".microts.v1.CreateDatabaseResponse\x12Q\n" +
	"\fDropDatabase\x12\x1f.microts.v1.DropDatabaseRequest\x1a .microts.v1.DropDatabaseResponse\x12?\n" +
	"\x06Health\x12\x19.microts.v1.HealthRequest\x1a\x1a.microts.v1.HealthResponseB'Z%codeberg.org/micro-ts/mts/types;typesb\x06proto3"

var (
	file_proto_microts_proto_rawDescOnce sync.Once
	file_proto_microts_proto_rawDescData []byte
)

func file_proto_microts_proto_rawDescGZIP() []byte {
	file_proto_microts_proto_rawDescOnce.Do(func() {
		file_proto_microts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_microts_proto_rawDesc), len(file_proto_microts_proto_rawDesc)))
	})
	return file_proto_microts_proto_rawDescData
}

var file_proto_microts_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_microts_proto_goTypes = []any{
	(*FieldValue)(nil),                // 0: microts.v1.FieldValue
	(*Point)(nil),                     // 1: microts.v1.Point
	(*PointRow)(nil),                  // 2: microts.v1.PointRow
	(*WriteRequest)(nil),              // 3: microts.v1.WriteRequest
	(*WriteBatchRequest)(nil),         // 4: microts.v1.WriteBatchRequest
	(*WriteResponse)(nil),             // 5: microts.v1.WriteResponse
	(*WriteBatchResponse)(nil),        // 6: microts.v1.WriteBatchResponse
	(*QueryRangeRequest)(nil),         // 7: microts.v1.QueryRangeRequest
	(*Row)(nil),                       // 8: microts.v1.Row
	(*QueryRangeResponse)(nil),        // 9: microts.v1.QueryRangeResponse
	(*ListMeasurementsRequest)(nil),   // 10: microts.v1.ListMeasurementsRequest
	(*ListMeasurementsResponse)(nil),  // 11: microts.v1.ListMeasurementsResponse
	(*CreateMeasurementRequest)(nil),  // 12: microts.v1.CreateMeasurementRequest
	(*CreateMeasurementResponse)(nil), // 13: microts.v1.CreateMeasurementResponse
	(*DropMeasurementRequest)(nil),    // 14: microts.v1.DropMeasurementRequest
	(*DropMeasurementResponse)(nil),   // 15: microts.v1.DropMeasurementResponse
	(*ListDatabasesRequest)(nil),      // 16: microts.v1.ListDatabasesRequest
	(*ListDatabasesResponse)(nil),     // 17: microts.v1.ListDatabasesResponse
	(*CreateDatabaseRequest)(nil),     // 18: microts.v1.CreateDatabaseRequest
	(*CreateDatabaseResponse)(nil),    // 19: microts.v1.CreateDatabaseResponse
	(*DropDatabaseRequest)(nil),       // 20: microts.v1.DropDatabaseRequest
	(*DropDatabaseResponse)(nil),      // 21: microts.v1.DropDatabaseResponse
	(*HealthRequest)(nil),             // 22: microts.v1.HealthRequest
	(*HealthResponse)(nil),            // 23: microts.v1.HealthResponse
	(*MemTableConfig)(nil),            // 24: microts.v1.MemTableConfig
	(*Config)(nil),                    // 25: microts.v1.Config
	nil,                               // 26: microts.v1.Point.TagsEntry
	nil,                               // 27: microts.v1.Point.FieldsEntry
	nil,                               // 28: microts.v1.PointRow.TagsEntry
	nil,                               // 29: microts.v1.PointRow.FieldsEntry
	nil,                               // 30: microts.v1.WriteRequest.TagsEntry
	nil,                               // 31: microts.v1.WriteRequest.FieldsEntry
	nil,                               // 32: microts.v1.QueryRangeRequest.TagsEntry
	nil,                               // 33: microts.v1.Row.TagsEntry
	nil,                               // 34: microts.v1.Row.FieldsEntry
}
var file_proto_microts_proto_depIdxs = []int32{
	26, // 0: microts.v1.Point.tags:type_name -> microts.v1.Point.TagsEntry
	27, // 1: microts.v1.Point.fields:type_name -> microts.v1.Point.FieldsEntry
	28, // 2: microts.v1.PointRow.tags:type_name -> microts.v1.PointRow.TagsEntry
	29, // 3: microts.v1.PointRow.fields:type_name -> microts.v1.PointRow.FieldsEntry
	30, // 4: microts.v1.WriteRequest.tags:type_name -> microts.v1.WriteRequest.TagsEntry
	31, // 5: microts.v1.WriteRequest.fields:type_name -> microts.v1.WriteRequest.FieldsEntry
	3,  // 6: microts.v1.WriteBatchRequest.points:type_name -> microts.v1.WriteRequest
	32, // 7: microts.v1.QueryRangeRequest.tags:type_name -> microts.v1.QueryRangeRequest.TagsEntry
	33, // 8: microts.v1.Row.tags:type_name -> microts.v1.Row.TagsEntry
	34, // 9: microts.v1.Row.fields:type_name -> microts.v1.Row.FieldsEntry
	8,  // 10: microts.v1.QueryRangeResponse.rows:type_name -> microts.v1.Row
	24, // 11: microts.v1.Config.mem_table_cfg:type_name -> microts.v1.MemTableConfig
	0,  // 12: microts.v1.Point.FieldsEntry.value:type_name -> microts.v1.FieldValue
	0,  // 13: microts.v1.PointRow.FieldsEntry.value:type_name -> microts.v1.FieldValue
	0,  // 14: microts.v1.WriteRequest.FieldsEntry.value:type_name -> microts.v1.FieldValue
	0,  // 15: microts.v1.Row.FieldsEntry.value:type_name -> microts.v1.FieldValue
	3,  // 16: microts.v1.MicroTS.Write:input_type -> microts.v1.WriteRequest
	4,  // 17: microts.v1.MicroTS.WriteBatch:input_type -> microts.v1.WriteBatchRequest
	7,  // 18: microts.v1.MicroTS.QueryRange:input_type -> microts.v1.QueryRangeRequest
	10, // 19: microts.v1.MicroTS.ListMeasurements:input_type -> microts.v1.ListMeasurementsRequest
	12, // 20: microts.v1.MicroTS.CreateMeasurement:input_type -> microts.v1.CreateMeasurementRequest
	14, // 21: microts.v1.MicroTS.DropMeasurement:input_type -> microts.v1.DropMeasurementRequest
	16, // 22: microts.v1.MicroTS.ListDatabases:input_type -> microts.v1.ListDatabasesRequest
	18, // 23: microts.v1.MicroTS.CreateDatabase:input_type -> microts.v1.CreateDatabaseRequest
	20, // 24: microts.v1.MicroTS.DropDatabase:input_type -> microts.v1.DropDatabaseRequest
	22, // 25: microts.v1.MicroTS.Health:input_type -> microts.v1.HealthRequest
	5,  // 26: microts.v1.MicroTS.Write:output_type -> microts.v1.WriteResponse
	6,  // 27: microts.v1.MicroTS.WriteBatch:output_type -> microts.v1.WriteBatchResponse
	9,  // 28: microts.v1.MicroTS.QueryRange:output_type -> microts.v1.QueryRangeResponse
	11, // 29: microts.v1.MicroTS.ListMeasurements:output_type -> microts.v1.ListMeasurementsResponse
	13, // 30: microts.v1.MicroTS.CreateMeasurement:output_type -> microts.v1.CreateMeasurementResponse
	15, // 31: microts.v1.MicroTS.DropMeasurement:output_type -> microts.v1.DropMeasurementResponse
	17, // 32: microts.v1.MicroTS.ListDatabases:output_type -> microts.v1.ListDatabasesResponse
	19, // 33: microts.v1.MicroTS.CreateDatabase:output_type -> microts.v1.CreateDatabaseResponse
	21, // 34: microts.v1.MicroTS.DropDatabase:output_type -> microts.v1.DropDatabaseResponse
	23, // 35: microts.v1.MicroTS.Health:output_type -> microts.v1.HealthResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_microts_proto_init() }
func file_proto_microts_proto_init() {
	if File_proto_microts_proto != nil {
		return
	}
	file_proto_microts_proto_msgTypes[0].OneofWrappers = []any{
		(*FieldValue_IntValue)(nil),
		(*FieldValue_FloatValue)(nil),
		(*FieldValue_StringValue)(nil),
		(*FieldValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_microts_proto_rawDesc), len(file_proto_microts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_microts_proto_goTypes,
		DependencyIndexes: file_proto_microts_proto_depIdxs,
		MessageInfos:      file_proto_microts_proto_msgTypes,
	}.Build()
	File_proto_microts_proto = out.File
	file_proto_microts_proto_goTypes = nil
	file_proto_microts_proto_depIdxs = nil
}
