// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/microts.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MicroTS_Write_FullMethodName             = "/microts.v1.MicroTS/Write"
	MicroTS_WriteBatch_FullMethodName        = "/microts.v1.MicroTS/WriteBatch"
	MicroTS_QueryRange_FullMethodName        = "/microts.v1.MicroTS/QueryRange"
	MicroTS_ListMeasurements_FullMethodName  = "/microts.v1.MicroTS/ListMeasurements"
	MicroTS_CreateMeasurement_FullMethodName = "/microts.v1.MicroTS/CreateMeasurement"
	MicroTS_DropMeasurement_FullMethodName   = "/microts.v1.MicroTS/DropMeasurement"
	MicroTS_ListDatabases_FullMethodName     = "/microts.v1.MicroTS/ListDatabases"
	MicroTS_CreateDatabase_FullMethodName    = "/microts.v1.MicroTS/CreateDatabase"
	MicroTS_DropDatabase_FullMethodName      = "/microts.v1.MicroTS/DropDatabase"
	MicroTS_Health_FullMethodName            = "/microts.v1.MicroTS/Health"
)

// MicroTSClient is the client API for MicroTS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # MicroTS 时序数据库服务
//
// 提供完整的时序数据库远程访问接口，包括：
//
//   - 数据写入：单点写入、批量写入
//   - 数据查询：范围查询、分页支持
//   - 元数据管理：数据库和 Measurement 的增删改查
//   - 健康检查：服务状态查询
//
// 并发安全：
//
//	所有 RPC 方法都可以从多个 goroutine 并发调用。
//	gRPC 框架保证每个请求在独立的 goroutine 中处理。
type MicroTSClient interface {
	// 单点写入
	//
	// 将单个数据点写入时序数据库。
	// 数据首先写入 WAL，然后写入 MemTable。
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	// 批量写入
	//
	// 批量写入多个数据点，吞吐量通常比单点写入高。
	// 批量写入不是原子操作，部分失败不会回滚已写入的点。
	WriteBatch(ctx context.Context, in *WriteBatchRequest, opts ...grpc.CallOption) (*WriteBatchResponse, error)
	// 范围查询
	//
	// 查询指定时间范围内的数据，支持字段过滤、标签过滤和分页。
	// 数据按时间戳升序返回。
	QueryRange(ctx context.Context, in *QueryRangeRequest, opts ...grpc.CallOption) (*QueryRangeResponse, error)
	// 列出 Measurement
	//
	// 返回指定数据库中的所有 Measurement 名称。
	// 如果数据库不存在，返回空列表。
	ListMeasurements(ctx context.Context, in *ListMeasurementsRequest, opts ...grpc.CallOption) (*ListMeasurementsResponse, error)
	// 创建 Measurement
	//
	// 在指定数据库中创建一个新的 Measurement。
	// 如果数据库不存在，会自动创建。
	// 如果 Measurement 已存在，不会返回错误。
	CreateMeasurement(ctx context.Context, in *CreateMeasurementRequest, opts ...grpc.CallOption) (*CreateMeasurementResponse, error)
	// 删除 Measurement
	//
	// 删除指定的 Measurement 及其所有元数据。
	// 注意：磁盘上的数据文件不会被立即删除。
	DropMeasurement(ctx context.Context, in *DropMeasurementRequest, opts ...grpc.CallOption) (*DropMeasurementResponse, error)
	// 列出数据库
	//
	// 返回所有数据库名称列表。
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error)
	// 创建数据库
	//
	// 创建一个新的数据库。
	// 如果数据库已存在，不会返回错误。
	CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error)
	// 删除数据库
	//
	// 删除指定的数据库及其所有 Measurement。
	// 警告：此操作会永久删除元数据，且不可恢复。
	DropDatabase(ctx context.Context, in *DropDatabaseRequest, opts ...grpc.CallOption) (*DropDatabaseResponse, error)
	// 健康检查
	//
	// 返回服务的健康状态，用于负载均衡器健康检查和监控。
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type microTSClient struct {
	cc grpc.ClientConnInterface
}

func NewMicroTSClient(cc grpc.ClientConnInterface) MicroTSClient {
	return &microTSClient{cc}
}

func (c *microTSClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, MicroTS_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microTSClient) WriteBatch(ctx context.Context, in *WriteBatchRequest, opts ...grpc.CallOption) (*WriteBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteBatchResponse)
	err := c.cc.Invoke(ctx, MicroTS_WriteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microTSClient) QueryRange(ctx context.Context, in *QueryRangeRequest, opts ...grpc.CallOption) (*QueryRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRangeResponse)
	err := c.cc.Invoke(ctx, MicroTS_QueryRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microTSClient) ListMeasurements(ctx context.Context, in *ListMeasurementsRequest, opts ...grpc.CallOption) (*ListMeasurementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMeasurementsResponse)
	err := c.cc.Invoke(ctx, MicroTS_ListMeasurements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microTSClient) CreateMeasurement(ctx context.Context, in *CreateMeasurementRequest, opts ...grpc.CallOption) (*CreateMeasurementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMeasurementResponse)
	err := c.cc.Invoke(ctx, MicroTS_CreateMeasurement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microTSClient) DropMeasurement(ctx context.Context, in *DropMeasurementRequest, opts ...grpc.CallOption) (*DropMeasurementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropMeasurementResponse)
	err := c.cc.Invoke(ctx, MicroTS_DropMeasurement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microTSClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabasesResponse)
	err := c.cc.Invoke(ctx, MicroTS_ListDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microTSClient) CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatabaseResponse)
	err := c.cc.Invoke(ctx, MicroTS_CreateDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microTSClient) DropDatabase(ctx context.Context, in *DropDatabaseRequest, opts ...grpc.CallOption) (*DropDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropDatabaseResponse)
	err := c.cc.Invoke(ctx, MicroTS_DropDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microTSClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MicroTS_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MicroTSServer is the server API for MicroTS service.
// All implementations must embed UnimplementedMicroTSServer
// for forward compatibility.
//
// # MicroTS 时序数据库服务
//
// 提供完整的时序数据库远程访问接口，包括：
//
//   - 数据写入：单点写入、批量写入
//   - 数据查询：范围查询、分页支持
//   - 元数据管理：数据库和 Measurement 的增删改查
//   - 健康检查：服务状态查询
//
// 并发安全：
//
//	所有 RPC 方法都可以从多个 goroutine 并发调用。
//	gRPC 框架保证每个请求在独立的 goroutine 中处理。
type MicroTSServer interface {
	// 单点写入
	//
	// 将单个数据点写入时序数据库。
	// 数据首先写入 WAL，然后写入 MemTable。
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	// 批量写入
	//
	// 批量写入多个数据点，吞吐量通常比单点写入高。
	// 批量写入不是原子操作，部分失败不会回滚已写入的点。
	WriteBatch(context.Context, *WriteBatchRequest) (*WriteBatchResponse, error)
	// 范围查询
	//
	// 查询指定时间范围内的数据，支持字段过滤、标签过滤和分页。
	// 数据按时间戳升序返回。
	QueryRange(context.Context, *QueryRangeRequest) (*QueryRangeResponse, error)
	// 列出 Measurement
	//
	// 返回指定数据库中的所有 Measurement 名称。
	// 如果数据库不存在，返回空列表。
	ListMeasurements(context.Context, *ListMeasurementsRequest) (*ListMeasurementsResponse, error)
	// 创建 Measurement
	//
	// 在指定数据库中创建一个新的 Measurement。
	// 如果数据库不存在，会自动创建。
	// 如果 Measurement 已存在，不会返回错误。
	CreateMeasurement(context.Context, *CreateMeasurementRequest) (*CreateMeasurementResponse, error)
	// 删除 Measurement
	//
	// 删除指定的 Measurement 及其所有元数据。
	// 注意：磁盘上的数据文件不会被立即删除。
	DropMeasurement(context.Context, *DropMeasurementRequest) (*DropMeasurementResponse, error)
	// 列出数据库
	//
	// 返回所有数据库名称列表。
	ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)
	// 创建数据库
	//
	// 创建一个新的数据库。
	// 如果数据库已存在，不会返回错误。
	CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error)
	// 删除数据库
	//
	// 删除指定的数据库及其所有 Measurement。
	// 警告：此操作会永久删除元数据，且不可恢复。
	DropDatabase(context.Context, *DropDatabaseRequest) (*DropDatabaseResponse, error)
	// 健康检查
	//
	// 返回服务的健康状态，用于负载均衡器健康检查和监控。
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMicroTSServer()
}

// UnimplementedMicroTSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMicroTSServer struct{}

func (UnimplementedMicroTSServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedMicroTSServer) WriteBatch(context.Context, *WriteBatchRequest) (*WriteBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteBatch not implemented")
}
func (UnimplementedMicroTSServer) QueryRange(context.Context, *QueryRangeRequest) (*QueryRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRange not implemented")
}
func (UnimplementedMicroTSServer) ListMeasurements(context.Context, *ListMeasurementsRequest) (*ListMeasurementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMeasurements not implemented")
}
func (UnimplementedMicroTSServer) CreateMeasurement(context.Context, *CreateMeasurementRequest) (*CreateMeasurementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMeasurement not implemented")
}
func (UnimplementedMicroTSServer) DropMeasurement(context.Context, *DropMeasurementRequest) (*DropMeasurementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropMeasurement not implemented")
}
func (UnimplementedMicroTSServer) ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatabases not implemented")
}
func (UnimplementedMicroTSServer) CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDatabase not implemented")
}
func (UnimplementedMicroTSServer) DropDatabase(context.Context, *DropDatabaseRequest) (*DropDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropDatabase not implemented")
}
func (UnimplementedMicroTSServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMicroTSServer) mustEmbedUnimplementedMicroTSServer() {}
func (UnimplementedMicroTSServer) testEmbeddedByValue()                 {}

// UnsafeMicroTSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicroTSServer will
// result in compilation errors.
type UnsafeMicroTSServer interface {
	mustEmbedUnimplementedMicroTSServer()
}

func RegisterMicroTSServer(s grpc.ServiceRegistrar, srv MicroTSServer) {
	// If the following call panics, it indicates UnimplementedMicroTSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MicroTS_ServiceDesc, srv)
}

func _MicroTS_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroTS_WriteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).WriteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_WriteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).WriteBatch(ctx, req.(*WriteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroTS_QueryRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).QueryRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_QueryRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).QueryRange(ctx, req.(*QueryRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroTS_ListMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMeasurementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).ListMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_ListMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).ListMeasurements(ctx, req.(*ListMeasurementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroTS_CreateMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).CreateMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_CreateMeasurement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).CreateMeasurement(ctx, req.(*CreateMeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroTS_DropMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropMeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).DropMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_DropMeasurement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).DropMeasurement(ctx, req.(*DropMeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroTS_ListDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).ListDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_ListDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).ListDatabases(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroTS_CreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).CreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_CreateDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).CreateDatabase(ctx, req.(*CreateDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroTS_DropDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).DropDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_DropDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).DropDatabase(ctx, req.(*DropDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroTS_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroTSServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicroTS_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroTSServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MicroTS_ServiceDesc is the grpc.ServiceDesc for MicroTS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MicroTS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microts.v1.MicroTS",
	HandlerType: (*MicroTSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _MicroTS_Write_Handler,
		},
		{
			MethodName: "WriteBatch",
			Handler:    _MicroTS_WriteBatch_Handler,
		},
		{
			MethodName: "QueryRange",
			Handler:    _MicroTS_QueryRange_Handler,
		},
		{
			MethodName: "ListMeasurements",
			Handler:    _MicroTS_ListMeasurements_Handler,
		},
		{
			MethodName: "CreateMeasurement",
			Handler:    _MicroTS_CreateMeasurement_Handler,
		},
		{
			MethodName: "DropMeasurement",
			Handler:    _MicroTS_DropMeasurement_Handler,
		},
		{
			MethodName: "ListDatabases",
			Handler:    _MicroTS_ListDatabases_Handler,
		},
		{
			MethodName: "CreateDatabase",
			Handler:    _MicroTS_CreateDatabase_Handler,
		},
		{
			MethodName: "DropDatabase",
			Handler:    _MicroTS_DropDatabase_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MicroTS_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/microts.proto",
}
